# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule: # Run workflow automatically
    - cron: '0 3 * * *' # Runs at 3:00

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: ./assets/github-contribution-grid-snake.gif
          svg_out_path: ./assets/github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: main
          message: 'Generate Contribution Snake'
